resources:
  Dbp\Relay\BaseOrganizationBundle\Entity\Organization:
    types: ['http://schema.org/Organization']
    shortName: 'BaseOrganization'
    normalizationContext:
      groups: ['BaseOrganization:output', 'LocalData:output']
      jsonld_embed_context: true
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\BaseOrganizationBundle\DataProvider\OrganizationDataProvider
        uriTemplate: '/base/organizations/{identifier}'
        openapiContext:
          tags: ["BaseOrganization"]
          parameters:
            - name: includeLocal
              in: query
              description: 'Local data attributes to include'
              type: string
              example: 'code'
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\BaseOrganizationBundle\DataProvider\OrganizationDataProvider
        uriTemplate: '/base/organizations'
        openapiContext:
          tags: ['BaseOrganization']
          parameters:
            - name: search
              in: query
              description: "Search filter (partial, case-insensitive text search on 'name' attribute)"
              required: false
              type: string
            - name: includeLocal
              in: query
              description: 'Local data attributes to include'
              type: string
              example: 'code'
            - name: queryLocal
              in: query
              description: 'Local query parameters to apply'
              type: string

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      localData:
        iri: 'https://schema.org/additionalProperty'
