services:
  Dbp\Relay\BaseOrganizationBundle\DataProvider\OrganizationDataProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseOrganizationBundle\Service\DummyOrganizationProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseOrganizationBundle\API\OrganizationProviderInterface:
    '@Dbp\Relay\BaseOrganizationBundle\Service\DummyOrganizationProvider'
