services:
  Dbp\Relay\BaseOrganizationBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseOrganizationBundle\Service\DummyOrganizationProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseOrganizationBundle\Service\DummyOrganizationsByPersonProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseOrganizationBundle\API\OrganizationProviderInterface:
    '@Dbp\Relay\BaseOrganizationBundle\Service\DummyOrganizationProvider'

  Dbp\Relay\BaseOrganizationBundle\API\OrganizationsByPersonProviderInterface:
    '@Dbp\Relay\BaseOrganizationBundle\Service\DummyOrganizationsByPersonProvider'
